// <auto-generated />
using Maalca.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Maalca.Infrastructure.Migrations
{
    // Escrito a mano (sin dotnet ef disponible) — a diferencia de los Designer.cs generados por
    // la herramienta, este NO sobreescribe BuildTargetModel (queda en el default vacío de la
    // clase base Migration). Eso es suficiente para que Database.Migrate() en runtime descubra
    // y aplique esta migración: lo único que EF necesita para el descubrimiento vía
    // MigrationsAssembly son estos dos atributos. BuildTargetModel solo lo usan las herramientas
    // de diseño (dotnet ef migrations add/script) para diffear contra el modelo actual, algo que
    // no hacemos en este flujo. Sin este archivo, esta migración era invisible para
    // Database.Migrate() y nunca se aplicó en producción — bug real reportado 2026-08-17.
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816150000_RemoveGiftCardAndCampaign")]
    partial class RemoveGiftCardAndCampaign
    {
    }
}
