// <auto-generated />
using Maalca.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Maalca.Infrastructure.Migrations
{
    // Ver comentario en 20260816150000_RemoveGiftCardAndCampaign.Designer.cs — mismo patrón
    // mínimo (solo atributos, sin BuildTargetModel), suficiente para que Database.Migrate()
    // descubra y aplique esta migración en runtime. Esta es la migración cuya ausencia causó el
    // error "relation TableReservations does not exist" (42P01) reportado en producción.
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816170000_AddTableReservations")]
    partial class AddTableReservations
    {
    }
}
